--15장 사용자 관리

--스키마 : 데이터 베이스에서 데이터 간 관계, 구조 제약조건 등
--        데이터를 저장, 관리하기 위해 정의한 데이터베이스 구조의 범위
--        - 데이터베이스에 접속한 사용자와 연결된 객체를 의미

--CONNECT SYS/ORACLE AS SYSDBA;
--ALTER USER HR IDENTIFIED BY 1234 ACCOUNT UNLOCK;

CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;  --insufficient privileges

CREATE TABLE TEMP(
    COL1 VARCHAR2(20),
    COL2 VARCHAR2(20)
);

GRANT SELECT ON TEMP TO ORCLSTUDY;  --SELECT을 TEMP에 권한부여

GRANT INSERT ON TEMP TO ORCLSTUDY;

--GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;  --한거번에 주는것도 가능

REVOKE SELECT , INSERT ON TEMP FROM ORCLSTUDY;

--사용자 생성 : CREATE USER
--권한부여    : GRANT
--권한 회수   : REVOKE


CREATE USER PREV_HW IDENTIFIED BY ORCL;
GRANT CREATE SESSION TO PREV_HW;



GRANT SELECT ON EMP TO PREV_HW;
GRANT SELECT ON DEPT TO PREV_HW;
GRANT SELECT ON SALGRADE TO PREV_HW;

SELECT * FROM HR.SALGRADE;

REVOKE SELECT ON SALGRADE FROM PREV_HW;




